### PR TITLE
Od itina

### PR DESCRIPTION
**Pull request by ODItina**
Update. Please review

### CODE REVIEW

**Review by patlichengine — COMMENTED** [review]
Your code looks good

**Review by patlichengine — CHANGES_REQUESTED** [review]
The methods look Good. When you use SQL Query in a code the underlying CommandType should be Text not StoredProcedure. Pls make the changes

**Comment by patlichengine** [comment]
Check the changes you need to make. But I like your codes

**Comment by ODItina** [comment]
Thank you sir. I will make the necessary changes ASAP

    On Monday, 16 March 2020, 09:38:41 GMT+1, Livinus Igwe <notifications@github.com> wrote:  
 
 


Check the changes you need to make. But I like your codes

**Pull request closed without merging**
